version: 1.0.{build}
os: Visual Studio 2015
skip_tags: true
configuration: Release

install:
    - cmd: git submodule update --init --recursive

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c release test\DeveMazeGenerator.Tests\DeveMazeGenerator.Tests.csproj
  
after_test:
  - cmd: dotnet pack -c Release src\DeveMazeGenerator\
  - cmd: Scripts\GoRepack.cmd

artifacts:
- path: Scripts\DeveMazeGeneratorCore.7z
  name: droppackage7z
- path: Scripts\DeveMazeGeneratorCore.zip
  name: droppackagezip
- path: 'src\DeveMazeGenerator\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage7z,droppackagezip,nugetPackages