version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - ps: .\scripts\set-version.ps1
  #- ps: .\scripts\download-fileoptimizer.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n  
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c release -p:ParallelizeTestCollections=false DeveImageOptimizer.Tests\DeveImageOptimizer.Tests.csproj
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\DeveImageOptimizer.Tests\bin\release\netcoreapp2.0\DeveImageOptimizer.Tests.dll -noshadow" -output:".\MyProject_coverage.xml"
  - codecov -f "MyProject_coverage.xml"
  
after_test:
  - cmd: dotnet pack -c Release DeveImageOptimizer\

artifacts:
- path: 'DeveImageOptimizer\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: nugetPackages,droppackage
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/