version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

environment:
  sonarqubetoken:
    secure: ppdeirHI9dsM7NpQgtwIRqXbiqhJZvIyHxOFhnME5HhRFS6IbYZqRppQi7fTqv37

before_build:
  - ps: .\scripts\set-version.ps1
  #- ps: .\scripts\download-fileoptimizer2.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n  
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  - choco install "msbuild-sonarqube-runner" -y

build_script:
  - cmd: dotnet build -c Release

test_script:
  #- cmd: dotnet test -c release -p:ParallelizeTestCollections=false DeveImageOptimizer.Tests\DeveImageOptimizer.Tests.csproj
  #- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\DeveImageOptimizer.Tests\bin\release\netcoreapp2.0\DeveImageOptimizer.Tests.dll -noshadow" -filter:"+[DeveImageOptimizer*]*" -output:".\DeveImageOptimizer.Coverage.xml"
  - SonarScanner.MSBuild.exe begin /k:"DeveImageOptimizer" /d:sonar.organization="devedse-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarqubetoken% /d:sonar.cs.opencover.reportsPaths=".\DeveImageOptimizer.Coverage.xml" /d:sonar.coverage.exclusions="DeveImageOptimizer.ConsoleApp/**/*.cs,DeveImageOptimizer.Tests/**/*.cs"
  - cmd: dotnet build -c Release
  - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\DeveImageOptimizer.Tests\DeveImageOptimizer.Tests.csproj -c Release --filter ShouldSkipForAppVeyor!=Yes" -oldstyle -returntargetcode -output:.\DeveImageOptimizer.Coverage.xml -filter:"+[DeveImageOptimizer*]* -[DeveImageOptimizer.Tests*]*"
  - SonarScanner.MSBuild.exe end /d:sonar.login=%sonarqubetoken%
  - codecov -f "DeveImageOptimizer.Coverage.xml"
  
after_test:
  - cmd: dotnet pack -c Release DeveImageOptimizer\

artifacts:
- path: 'DeveImageOptimizer\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: nugetPackages,droppackage
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/
